# Generated by Django 4.0.3 on 2022-04-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.outfit'),
        ),
        migrations.AlterField(
            model_name='outfitphoto',
            name='outfit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.outfit', verbose_name='Outfit'),
        ),
    ]
