# Generated by Django 4.0.3 on 2022-04-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_comment_photo_alter_outfitphoto_outfit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='outfit',
        ),
    ]
