# Generated by Django 4.0.3 on 2022-04-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_like_delete_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
