# Generated by Django 4.0.3 on 2022-04-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_like_created_remove_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfitphoto',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='outfitphoto',
            name='likes',
        ),
    ]
