# Generated by Django 4.0.3 on 2022-04-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipe',
            new_name='photo',
        ),
    ]
